const x = {
	Number: null,
	Product: "Alisse",
	GenericModelNumber: "NPKP",
	CustomModelNumber: "NPKP-N",
	FGID: "HW-NW-KP-S2-E",
	Features: {
		SYSTEM: { ValidKeys: ["HW"], InvalidKeys: [], CurrentValue: "HW" },
		WALLBOX_SHAPE: { ValidKeys: ["R", "S"], InvalidKeys: [], CurrentValue: "S" },
		COLUMNS: { ValidKeys: ["1", "2", "3"], InvalidKeys: [], CurrentValue: "2" },
		BUTTON_ARRAY: { ValidKeys: ["11", "13", "22", "31", "33"], InvalidKeys: [], CurrentValue: "33" },
		FACEPLATE_FINISH: { ValidKeys: ["AB", "AZ", "BRB", "GP", "CP", "SN", "BC", "BWH", "SWH", "AWH", "BL", "CU"], InvalidKeys: [], CurrentValue: "AZ" },
		LeadTime: { CurrentValue: 20, From: 20, To: 20, Step: 0 },
		ENGRAVING_SPECIFIED: { ValidKeys: ["TBD", "N", "Y"], InvalidKeys: [], CurrentValue: "TBD" },
		IS_DEMO: { ValidKeys: ["N", "Y"], InvalidKeys: [], CurrentValue: "N" },
		COUNTRY: {
			ValidKeys: [
				"BD",
				"BL",
				"BG",
				"BW",
				"CU",
				"EC",
				"FI",
				"HK",
				"HM",
				"HT",
				"IO",
				"LI",
				"LS",
				"MU",
				"NI",
				"PA",
				"PR",
				"RU",
				"SH",
				"AF",
				"AN",
				"BJ",
				"CN",
				"FR",
				"BM",
				"BT",
				"BV",
				"CD",
				"CY",
				"FJ",
				"GR",
				"MD",
				"ML",
				"MX",
				"MY",
				"PH",
				"RW",
				"SN",
				"VC",
				"AI",
				"AS",
				"CI",
				"ES",
				"FK",
				"FM",
				"IQ",
				"KP",
				"LK",
				"LT",
				"LV",
				"PE",
				"TK",
				"TM",
				"TT",
				"TV",
				"ZW",
				"AD",
				"AL",
				"AX",
				"BY",
				"CL",
				"CX",
				"DE",
				"DO",
				"DZ",
				"GA",
				"HR",
				"IS",
				"NC",
				"NU",
				"PN",
				"SJ",
				"TC",
				"VG",
				"WS",
				"ZA",
				"AE",
				"AO",
				"AZ",
				"BO",
				"DK",
				"EE",
				"GI",
				"GS",
				"JE",
				"KG",
				"KW",
				"MQ",
				"PS",
				"TH",
				"VN",
				"ZM",
				"CF",
				"KN",
				"MF",
				"NA",
				"PK",
				"PT",
				"SI",
				"BI",
				"BS",
				"GF",
				"GN",
				"KM",
				"MK",
				"MP",
				"MT",
				"MV",
				"NG",
				"PF",
				"RE",
				"SL",
				"TG",
				"TW",
				"VU",
				"AM",
				"AT",
				"BB",
				"CK",
				"CM",
				"CV",
				"ET",
				"GH",
				"HN",
				"JM",
				"JP",
				"KY",
				"LY",
				"MM",
				"OM",
				"QA",
				"RO",
				"SD",
				"SX",
				"SY",
				"VE",
				"YT",
				"GE",
				"IT",
				"KH",
				"MN",
				"NR",
				"SS",
				"TR",
				"US",
				"AR",
				"BH",
				"CA",
				"CR",
				"FO",
				"GG",
				"GW",
				"ID",
				"IL",
				"MA",
				"MR",
				"NO",
				"NZ",
				"PM",
				"SB",
				"SK",
				"ST",
				"TO",
				"TZ",
				"UM",
				"VA",
				"AG",
				"AW",
				"BQ",
				"CC",
				"EG",
				"GM",
				"GP",
				"GT",
				"LU",
				"MC",
				"NP",
				"RS",
				"SA",
				"SR",
				"UA",
				"VI",
				"BF",
				"BN",
				"CH",
				"EH",
				"GQ",
				"KR",
				"LA",
				"LR",
				"MH",
				"NE",
				"PL",
				"PY",
				"SM",
				"SV",
				"UY",
				"BR",
				"ER",
				"GU",
				"KZ",
				"NF",
				"SG",
				"TJ",
				"UG",
				"YE",
				"AQ",
				"BE",
				"BZ",
				"CG",
				"CW",
				"DM",
				"GB",
				"IR",
				"LC",
				"MG",
				"MW",
				"SC",
				"TF",
				"TN",
				"BA",
				"CO",
				"CZ",
				"HU",
				"IN",
				"JO",
				"KE",
				"ME",
				"MO",
				"MZ",
				"NL",
				"PG",
				"PW",
				"TD",
				"TL",
				"WF",
				"AU",
				"BU",
				"DJ",
				"GD",
				"GL",
				"GY",
				"IE",
				"KI",
				"LB",
				"MS",
				"SE",
				"SO",
				"SZ",
				"UZ",
			],
			InvalidKeys: [],
			CurrentValue: "US",
		},
		COMPONENTS: { ValidKeys: ["KB", "KO", "KBW"], InvalidKeys: [], CurrentValue: "KO" },
		ProductDetails: { ValidKeys: ["NPKP"], InvalidKeys: [], CurrentValue: "NPKP" },
		Price: { CurrentValue: 525.0, From: 525.0, To: 525.0, Step: 0.0, Unit: "USD" },
	},
	IsFullyConfigured: false,
	UsedElevatedAccess: false,
	AdditionalAttributes: [{ Name: "PSTORE_MODEL", Value: "HW-S-AZ-S-10101-10101-AZ-E" }],
	Errors: [],
	Warnings: [
		{
			Message: 'The Alisse keypad requires the use of a Base Unit for installation.  "Keypad Only" should be selected for replacement keypads where a Base Unit is already present.',
			Assertion: 'The Alisse keypad requires the use of a Base Unit for installation.  "Keypad Only" should be selected for replacement keypads where a Base Unit is already present.',
			Type: 5,
			FeatureName: null,
		},
	],
	IsConfigured: true,
	RevisedSelections: null,
}
